### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by amiyasahu** [amiyasahu/q2a-social-share#13]
- [x] Add stumbleupon share 
- [x] Add Telegram sharing option 
- [x] Width fix for older themes for the side bar widget 
- [x] Add support for blog plugin
